version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew bootWar
artifacts:
  files:
    - build/libs/hms-v3-0.0.1-SNAPSHOT.jar
    - .ebextensions\fixpath.config
  discard-paths: yes